[project]
name = "lexigo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.25.0",
    "aiosqlite>=0.22.1",
    "groq>=1.0.0",
    "pydantic-settings>=2.13.0",
    "sqlalchemy>=2.0.46",
]
